services:
  postgres:
    container_name: 'postgres'
    image: 'docker.io/library/postgres:16-bookworm'
    ports:
      - '5432:5432'
    volumes:
      - 'myapp-pg:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'myapp'
  myapp:
    container_name: 'web'
    build:
      context: './'
      dockerfile: 'containerfile'
    env_file: './.env'
    ports:
      - '$PORT:$PORT'
  prometheus:
    container_name: 'prometheus'
    image: 'docker.io/prom/prometheus:v2.54.1'
    ports:
      - '9090:9090'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    environment:
      - 'GOMAXPROCS=$GOMAXPROCS'
      - 'GOMEMLIMIT=$GOMEMLIMIT'
    depends_on:
      - 'myapp'
  grafana:
    container_name: 'grafana'
    image: 'docker.io/grafana/grafana:11.2.2'
    ports:
      - '3000:3000'
    volumes:
      - './grafana/sources.yaml:/etc/grafana/provisioning/datasources/sources.yaml'
      - './grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml'
      - './grafana/myapp.json:/etc/grafana/provisioning/dashboards/myapp.json'
    depends_on:
      - 'myapp'
      - 'prometheus'
volumes:
  myapp-pg:
