services:
  myapp:
    build:
      context: '.'
      dockerfile: 'containerfile'
    env_file: '.env'
    ports:
      - '$PORT:$PORT'
    environment:
      - 'GOMAXPROCS=$GOMAXPROCS'
      - 'GOMEMLIMIT=$GOMEMLIMIT'
      - 'PORT=$PORT'
  prometheus:
    image: 'docker.io/prom/prometheus:v2.54.1'
    ports:
      - '9090:9090'
    volumes:
      - './prometheus.yaml:/etc/config.yaml:ro'
    args:
      - '--config.file=/etc/config.yaml'
    environment:
      - 'GOMAXPROCS=$GOMAXPROCS'
      - 'GOMEMLIMIT=$GOMEMLIMIT'
    depends_on:
      - 'myapp'
  grafana:
    image: 'docker.io/grafana/grafana:11.2.2'
    ports:
      - '3000:3000'
    volumes:
      - './grafana.db:/var/lib/grafana/grafana.db'
    depends_on:
      - 'myapp'
      - 'prometheus'
