{
 "title": "API Monitoring Dashboard - Golden Signals",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "panels": [
  { "title": "Latency - Traffic - Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency (p50/90) by path",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le, path))",
     "legendFormat": "90th percentile - {{ path }}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[$__rate_interval])) by (le, path))",
     "legendFormat": "50th percentile - {{ path }}"
    }
   ]
  },
  {
   "title": "Traffic Rate by Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[$__rate_interval])) by (code)",
     "legendFormat": "HTTP {{ code }}"
    }
   ]
  },
  {
   "title": "Errors/Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[$__rate_interval]))",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(rate(http_errors_total[$__rate_interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  { "title": "Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Client p99 Latency Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(k6_http_req_duration_p99[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Client Sessions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "k6_vus", "legendFormat": "__auto" }
   ]
  }
 ]
}