apiVersion: 1

datasources:
- id: 1
  uid: be1abogsemnswc
  orgId: 1
  name: prometheus
  type: prometheus
  typeName: Prometheus
  typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
  access: proxy
  url: http://prometheus:${PROMETHEUS_PORT}
  user: ""
  database: ""
  basicAuth: false
  isDefault: true
  jsonData:
    httpMethod: POST
  readOnly: false
